# -*- coding: utf-8 -*-
"""lab12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KQ7UTWBoRg0o16W6oaKO29xAwdBdqCyq
"""

import pandas as pd
import pymc as pm
import numpy as np
import arviz as az
import matplotlib.pyplot as plt

file_path = 'date_promovare_examen.csv'
data = pd.read_csv(file_path)

print("\nDistribuția clasei (Promovare):")
print(data['Promovare'].value_counts())

with pm.Model() as logistic_model:
    beta_0 = pm.Normal("beta_0", mu=0, sigma=10)
    beta_studiu = pm.Normal("beta_studiu", mu=0, sigma=10)
    beta_somn = pm.Normal("beta_somn", mu=0, sigma=10)

    logit_p = beta_0 + beta_studiu * data['Ore_Studiu'] + beta_somn * data['Ore_Somn']
    p = pm.math.sigmoid(logit_p)
    y_obs = pm.Bernoulli("y_obs", p=p, observed=data['Promovare'])
    trace = pm.sample(2000, tune=1000, cores=2)


print("\nRezumatul distribuțiilor parametrilor:")
summary = az.summary(trace)
print(summary)

beta_0_mean = trace.posterior['beta_0'].mean().item()
beta_studiu_mean = trace.posterior['beta_studiu'].mean().item()
beta_somn_mean = trace.posterior['beta_somn'].mean().item()

print("\nParametri medii din model:")
print(f"Intercept: {beta_0_mean:.2f}, Coeficient Ore_Studiu: {beta_studiu_mean:.2f}, Coeficient Ore_Somn: {beta_somn_mean:.2f}")

ore_studiu = np.linspace(data['Ore_Studiu'].min(), data['Ore_Studiu'].max(), 100)
ore_somn = -(beta_0_mean + beta_studiu_mean * ore_studiu) / beta_somn_mean

plt.figure(figsize=(8, 6))
plt.scatter(data['Ore_Studiu'], data['Ore_Somn'], c=data['Promovare'], cmap='coolwarm', label='Datele')
plt.plot(ore_studiu, ore_somn, color='black', label='Granița decizională')
plt.xlabel('Ore Studiu')
plt.ylabel('Ore Somn')
plt.title('Regresie Logistică Bayesiană - Granița Decizională')
plt.legend()
plt.show()