# -*- coding: utf-8 -*-
"""lab11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1okfVcj6k5wbUT2f1xqZQKEJ7dDtHx3gr
"""

import numpy as np
import pandas as pd
import pymc as pm
import arviz as az

data = pd.read_csv('real_estate_data.csv')

with pm.Model() as model:
    alpha = pm.Normal('alpha', mu=0, sigma=10)
    beta1 = pm.Normal('beta1', mu=0, sigma=10)
    beta2 = pm.Normal('beta2', mu=0, sigma=10)
    beta3 = pm.Normal('beta3', mu=0, sigma=10)
    sigma = pm.HalfNormal('sigma', sigma=1)

    mu = alpha + beta1 * data['Surface_area'] + beta2 * data['Rooms'] + beta3 * data['Distance_to_center']

    Y_obs = pm.Normal('Y_obs', mu=mu, sigma=sigma, observed=data['Price'])

    trace = pm.sample(1000, return_inferencedata=True)

az.plot_trace(trace)
az.summary(trace)
# Suprafața Utilă (beta1):
# Influencă Pozitivă: Creșterea suprafeței duce la creșterea prețului, conform tendințelor pieței imobiliare.

# Numărul de Camere (beta2):
# Influencă Pozitivă: Mai multe camere cresc prețul.

# Distanța față de Centrul Orașului (beta3):
# Influencă Negativă: Apartamentele mai îndepărtate de centru costă mai puțin, valoarea scăzând cu distanța.